### ISSUE TITLE
Metafields can't be loaded in snippet

### ISSUE THREAD

**Issue by Kyniu** [dreamcommerce/shop-appstore-lib#5]
I'm trying to load metafields in snippets, but it has stopped work (earlier wokred fine).
My metafields are in database and I can get them like this:

```php
$resultMetafields = $rMetafield->filters(array(
                'namespace' => 'STARBONUS'
            ))->get('SYSTEM');

            var_dump($resultMetafields);
```

Gives me:

```php
array (size=16)
.
.
.
          3 => 
            object(ArrayObject)[414]
              private 'storage' => 
                array (size=6)
                  'metafield_id' => string '1175' (length=4)
                  'object' => string 'SYSTEM' (length=6)
                  'key' => string 'integration_version' (length=19)
                  'namespace' => string 'STARBONUS' (length=9)
                  'description' => string 'asdfvgbfffffn' (length=13)
                  'type' => string '3' (length=1)


.
.
.
```

But in snipped:

```smarty
{metafield.system.STARBONUS.integration_version}
```

gives me empty result.

According to the documentation it is correct. Something changed?

**Comment by er1z** [comment]
Confirmed.

**Comment by er1z** [comment]
What is your shop version?

**Comment by Kyniu** [comment]
You mean Shoper version? 5.7.4

**Comment by Kyniu** [comment]
@er1z ?

**Comment by er1z** [comment]
We've found what's wrong and it will be fixed upon next release. Soon. (:

**Comment by deallas** [comment]
Fixed

**Comment by Kyniu** [comment]
Still not working in my application. I have the same problem. I have updated 'shop-appstore-lib' to 0.2.15, but I can't see metafields value in snippets on page.

**Comment by deallas** [comment]
Could you tell me which devshop / application has the problem ?

**Comment by Kyniu** [comment]
https://devshop-96670.shoparena.pl/
application ID:	f0de0729b47514193b74962389d4b44a

**Comment by deallas** [comment]
Eh, there is another bug who will be fixed in release 5.7.5 (early January). You can't use metafields in snippets if you have any permissions to "additional fields for objects". Please remove all metafields via API -> revoke permissions to "additional fields for objects" -> add metafields (you can do it without any additional permissions) and ... should work fine.

**Comment by Kyniu** [comment]
There is another problem. I'm trying to get my metafileds.
```php
$rMetafield = new \DreamCommerce\Resource\Metafield($client);
$resultMetafields = $rMetafield->filters(array(
      'namespace' => 'STARBONUS'
))->get('SYSTEM');
```
Result:
```php
object(DreamCommerce\ResourceList)[376]
  public 'count' => string '0' (length=1)
  public 'page' => int 1
  public 'pages' => int 0
  private 'storage' (ArrayObject) => 
    object(ArrayObject)[257]
      private 'storage' => 
        array (size=0)
          empty
```
Well, I haven't registered metafields. But, when I try add new with the same namespace:
```php
$data = array(
       'namespace' => 'STARBONUS',
       'key' => 'SOME_FIELD',
       'type' => \DreamCommerce\Resource\Metafield::TYPE_STRING
);

$result = $rMetafield->post('SYSTEM', $data);
```
 I have an exception: "This metafield is already registered".

Could you explain me why?

**Comment by er1z** [comment]
If you have granted a permission on metafields, you have an access to something like "global scope of metafields" which is NOT associated with a particular application.

Thus, if an application is being removed, created metafield is untouched. 

You have granted permissions, created a metafield, revoked permissions and then - you're now trying to create a metafield. So that - an error you quoted is raised.

We deleted this orphan metafield for you.
